kind: Service
apiVersion: v1
metadata:
  name: as-authentication-svc
spec:
  selector:
    app: as-authentication
  ports:
  - protocol: TCP
    port: 9001
---
# PAYMENT SERVICE DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-authentication
  labels:
    app: as-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-authentication
  template:
    metadata:
      labels:
        app: as-authentication
      annotations:
        sidecar.opentelemetry.io/inject: "true" 
    spec:
      containers:
      - name:  as-authentication
        image: ghcr.io/awesome-sphere/as-authentication/as-authentication:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authen-secret
              key: SECRET_KEY
        - name: ISSUER
          valueFrom:
            secretKeyRef:
              name: authen-secret
              key: ISSUER
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: authen-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: authen-secret
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_PASSWORD
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
