kind: Service
apiVersion: v1
metadata:
  name: as-booking-svc
spec:
  selector:
    app: as-booking
  ports:
  - protocol: TCP
    port: 9009
---
# BOOKING SERVICE DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-booking
  labels:
    app: as-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-booking
  template:
    metadata:
      labels:
        app: as-booking
      annotations:
        sidecar.opentelemetry.io/inject: "true" 
    spec:
      containers:
      - name:  as-booking
        image: ghcr.io/awesome-sphere/as-booking/as-booking:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9009
        env:
        - name: KAFKA_BOOKING_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_BOOKING_TOPIC_NAME
        - name: KAFKA_CANCEL_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_CANCEL_TOPIC_NAME
        - name: KAFKA_ADDR
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_ADDR
        - name: KAFKA_BOOKING_TOPIC_PARTITION
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_BOOKING_TOPIC_PARTITION
        - name: KAFKA_CANCEL_TOPIC_PARTITION
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_CANCEL_TOPIC_PARTITION
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_DB
        - name: THEATER_AMOUNT
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: THEATER_AMOUNT
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
# BOOKING CONSUMER DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-booking-consumer
  labels:
    app: as-booking-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: as-booking-consumer
  template:
    metadata:
      labels:
        app: as-booking-consumer
      annotations:
        sidecar.opentelemetry.io/inject: "true" 
    spec:
      containers:
      - name:  as-booking-consumer
        image: ghcr.io/awesome-sphere/as-booking/as-booking:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9009
        env:
        - name: KAFKA_BOOKING_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_BOOKING_TOPIC_NAME
        - name: KAFKA_CANCEL_TOPIC_NAME
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_CANCEL_TOPIC_NAME
        - name: KAFKA_ADDR
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_ADDR
        - name: KAFKA_BOOKING_TOPIC_PARTITION
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_BOOKING_TOPIC_PARTITION
        - name: KAFKA_CANCEL_TOPIC_PARTITION
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: KAFKA_CANCEL_TOPIC_PARTITION
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: POSTGRES_DB
        - name: THEATER_AMOUNT
          valueFrom:
            secretKeyRef:
              name: as-booking-secret
              key: THEATER_AMOUNT
      imagePullSecrets:
      - name: dockerconfigjson-github-com