kind: Service
apiVersion: v1
metadata:
  name: as-general-svc
spec:
  selector:
    app: as-general
  ports:
  - protocol: TCP
    port: 9002
---
# GENERAL SERVICE DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-general
  labels:
    app: as-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-general
  template:
    metadata:
      labels:
        app: as-general
      annotations:
        sidecar.opentelemetry.io/inject: "true" 
    spec:
      containers:
      - name:  as-general
        image: ghcr.io/awesome-sphere/as-general/as-general:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9002
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: MINIO_SECRET_KEY
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: general-secret
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-general-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-general-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-general-secret
              key: POSTGRES_PASSWORD
      imagePullSecrets:
      - name: dockerconfigjson-github-com
