kind: Service
apiVersion: v1
metadata:
  name: as-payment-svc
spec:
  selector:
    app: as-payment
  ports:
  - protocol: TCP
    port: 9003
---
# PAYMENT SERVICE DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-payment
  labels:
    app: as-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-payment
  template:
    metadata:
      labels:
        app: as-payment
      annotations:
        sidecar.opentelemetry.io/inject: "true" 
    spec:
      containers:
      - name:  as-payment
        image: ghcr.io/awesome-sphere/as-payment/as-payment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
        env:
        - name: KAFKA_ADDR
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: KAFKA_ADDR
        - name: KAFKA_TOPIC_PARTITION
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: KAFKA_TOPIC_PARTITION
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_PASSWORD
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
# PAYMENT CONSUMER DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-payment-consumer
  labels:
    app: as-payment-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as-payment-consumer
  template:
    metadata:
      labels:
        app: as-payment-consumer
    spec:
      containers:
      - name:  as-payment-consumer
        image: ghcr.io/awesome-sphere/as-payment-consumer/as-payment-consumer:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_ADDR
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: KAFKA_ADDR
        - name: KAFKA_TOPIC_PARTITION
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: KAFKA_TOPIC_PARTITION
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_PASSWORD
      imagePullSecrets:
      - name: dockerconfigjson-github-com