apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-payment-pv
  labels:
    type: local
    app: postgres-payment
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-payment-pvc
  labels:
    app: postgres-payment
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-payment
  template:
    metadata:
      labels:
        app: postgres-payment
    spec:
      containers:
      - name: postgres-payment
        image: postgres:12.10-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-payment-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/user-data
          name: postgres-payment-data
      volumes:
      - name: postgres-payment-data
        persistentVolumeClaim:
          claimName: postgres-payment-pvc
      imagePullSecrets:
      - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-payment
  labels:
    app: postgres-payment
spec:
  ports:
    - port: 5434
      targetPort: 5432
  selector:
    app: postgres-payment
  # NOTE: Remove this when deployed
  type: LoadBalancer